# Generated by Django 4.2.2 on 2023-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivemain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(upload_to='user_uploads/'),
        ),
    ]
