# Generated by Django 4.2.2 on 2023-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivemain', '0002_alter_mymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(upload_to='my_image'),
        ),
    ]
